-- AlterEnum
ALTER TYPE "ProofRequestStatus" ADD VALUE 'PENDING_FINAL';

-- AlterTable
ALTER TABLE "Campaign" ADD COLUMN     "durationDays" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "startAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "endAt" DROP NOT NULL;
